# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d15cb9f356d124acf37d90a7c66c1c443c536b9b8f35f28697effc79e6087aee6e6fd76eea6ae40dcd306f6bc763d86139d2e2e59a9f8c10c85b682be62c1cd

test:
  secret_key_base: b3c48b6b0029a7f6d0db9ff632d8e94697217bdfffc5cafba1ff6b7a2a4a0cfd943b7d0f69bc764a877e77db800b0a8f3f772f556c25432b638fa555bd2657f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
